package main.java.model.info;

import org.jetbrains.annotations.NotNull;

import java.io.Serializable;

/**
 * All the extra information associated with a entry
 */
public class EntryInfo implements Serializable {
    // ---------------- Insecure fields ----------------
    /**
     * The title of this entry e.g. Facebook, Gmail, etc.
     */
    @NotNull
    public final String title;

    /**
     * The user name to this entry's account
     */
    @NotNull
    public final String username;

    // ---------------- Secure fields ----------------
    /**
     * This is the password for the entry which is encrypted by the team password.
     */
    @NotNull
    public final String password;

    /**
     * The IV used to encrypt this password.
     */
    @NotNull
    public final String iv;


    //Autogenerated

    public EntryInfo(@NotNull String title, @NotNull String username, @NotNull String password, @NotNull String iv) {
        this.title = title;
        this.username = username;
        this.password = password;
        this.iv = iv;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        EntryInfo entryInfo = (EntryInfo) o;

        if (!title.equals(entryInfo.title)) return false;
        if (!username.equals(entryInfo.username)) return false;
        if (!password.equals(entryInfo.password)) return false;
        return iv.equals(entryInfo.iv);

    }

    @Override
    public int hashCode() {
        int result = title.hashCode();
        result = 31 * result + username.hashCode();
        result = 31 * result + password.hashCode();
        result = 31 * result + iv.hashCode();
        return result;
    }
}
