package main.java.logging;

import org.jetbrains.annotations.NotNull;

import javax.persistence.*;
import java.util.Date;

/**
 * A log entry
 */
@Entity
@Table(name = "LOGS")
public class LogEntry {
    /**
     * unique ID for each log entry
     */
    @Id
    @GeneratedValue
    @Column(name = "log_entry_id")
    private int id;

    /**
     * Timestamp for when the log was created
     */
    @NotNull
    @Column(name = "timestamp", nullable = false)
    private Date time;

    /**
     * The log level
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "level", nullable = false)
    private LogLevel level;

    /**
     * Relevant user
     */
    @Column(name = "user_id")
    private int uid;

    /**
     * Relevant team
     */
    @Column(name = "team_id")
    private int tid;

    /**
     * Relevant entry
     */
    @Column(name = "entry_id")
    private int eid;

    /**
     * Relevant ip address
     */
    @NotNull
    @Column(name = "ip_address", nullable = false)
    private String ipAddress;

    /**
     * Message of the log
     */
    @NotNull
    @Column(name = "message", nullable = false)
    private String message;

    private LogEntry() {
        this(LogLevel.DEBUG, ""); //Call other constructor to eliminate warnings. Hibernate will overwrite all fields.
    }

    /**
     * Use this constructor to create a log entry. Set the other fields
     * in the log as necessary using setters.
     * <p>
     * Automatically timestamps the message
     */
    public LogEntry(@NotNull LogLevel level, @NotNull String message) {
        //Required fields
        this.level = level;
        this.message = message;

        this.time = new Date(); //Timestamp

        //Default values
        this.uid = LogConstants.NO_USER;
        this.tid = LogConstants.NO_TEAM;
        this.eid = LogConstants.NO_ENTRY;
        this.ipAddress = LogConstants.NO_IP;
    }


    //Below is all auto-generated by intellij. Please regenerate if fields change
    //---------------------------------------------------------------


    @Override
    public String toString() {
        return "LogEntry{" +
                "id=" + id +
                ", time=" + time +
                ", level=" + level +
                ", uid=" + uid +
                ", tid=" + tid +
                ", eid=" + eid +
                ", ipAddress='" + ipAddress + '\'' +
                ", message='" + message + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LogEntry logEntry = (LogEntry) o;

        if (id != logEntry.id) return false;
        if (uid != logEntry.uid) return false;
        if (tid != logEntry.tid) return false;
        if (eid != logEntry.eid) return false;
        if (!time.equals(logEntry.time)) return false;
        if (level != logEntry.level) return false;
        if (!ipAddress.equals(logEntry.ipAddress)) return false;
        return message.equals(logEntry.message);

    }

    @Override
    public int hashCode() {
        int result = id;
        result = 31 * result + time.hashCode();
        result = 31 * result + level.hashCode();
        result = 31 * result + uid;
        result = 31 * result + tid;
        result = 31 * result + eid;
        result = 31 * result + ipAddress.hashCode();
        result = 31 * result + message.hashCode();
        return result;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public @NotNull Date getTime() {
        return time;
    }

    public void setTime(@NotNull Date time) {
        this.time = time;
    }

    public @NotNull LogLevel getLevel() {
        return level;
    }

    public void setLevel(@NotNull LogLevel level) {
        this.level = level;
    }

    public int getUid() {
        return uid;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public int getTid() {
        return tid;
    }

    public void setTid(int tid) {
        this.tid = tid;
    }

    public int getEid() {
        return eid;
    }

    public void setEid(int eid) {
        this.eid = eid;
    }

    public @NotNull String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(@NotNull String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public @NotNull String getMessage() {
        return message;
    }

    public void setMessage(@NotNull String message) {
        this.message = message;
    }
}